### ISSUE TITLE
Prawn-gmagick conflit with RMagick

### ISSUE THREAD

**Issue by nusdon** [packetmonkey/prawn-gmagick#11]
Hi there,

I'm using the rmagick and prawn-gmagick gems. When I run rails server, I get the following error:

```
Exiting
/home/macon10/.rvm/gems/ruby-2.1.2/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require': This installation of RMagick was configured with ImageMagick 6.7.7 but GraphicsMagick 1.3.18 is in use. (RuntimeError)
```

Any suggestions?

Thanks,

**Comment by packetmonkey** [comment]
Sadly not really. I don't use rmagick and taking a quick glance though the dependency trees I don't think either RMagick or prawn-gmagick is using polyglot.

So I don't think I can be of much help here. If you can sort out a way for prawn-gmagick to play nicer with other gems I would be happy to hear about it, but otherwise I'm not sure what I can do to stay out of the way of rmagick, given they use entirely different libraries and namespaces.

Thanks
